FROM php:8.2-apache

RUN docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli
    
# Install PDO MySQL extension and its dependencies
RUN apt-get update \
    && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo_mysql

# Install MySQL client
RUN apt-get install -y default-mysql-client
    
COPY . /var/www/html/
WORKDIR /var/www/html/

# Enable PDO MySQL extension in php.ini
RUN echo "extension=pdo_mysql.so" > /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
